cache:
  paths:
  - node_modules/
  - out/

stages:
  - deploy

build:
  stage: deploy
  script:
    - npm install
    - npm run compile
    - npm run copyfile
  only:
    - master
    - develop
    - /^feature/.*$/
    - /^fix/.*$/

deploy:
  stage: deploy
  before_script:
    - npm i -g vsce
  script:
    - vsce package
  only:
    - master
  artifacts:
    paths:
    - lang-4d-support-0.0.1.vsix