cache:
  paths:
  - node_modules/

stages:
  - deploy

build:
  stage: deploy
  script:
    - npm install
    - mkdir out/syntaxes
    - mkdir out/support
    - npm run compile
    - npm run copyfile
  only:
    - master
    - develop
    - /^release/.*$/
    - /^testing/.*$/

deploy:
  stage: deploy
  before_script:
    - npm i -g vsce
  script:
    - vsce package
  only:
    - master
  artifacts:
    paths:
    - out